### ISSUE TITLE
Why does the extension needs to access Tencent Cloud?

### ISSUE THREAD

**Issue by melMass** [Tencent/LuaHelper#142]
Hi,

Is there a way to optout?

Thanks

https://github.com/Tencent/LuaHelper/blob/cc916454171f5d70f18ff2bc6229ba2059d5b9f0/luahelper-lsp/langserver/get_online_req.go#L37

<img width="714" alt="image" src="https://user-images.githubusercontent.com/7041726/209983383-65671eaf-2d4f-4676-b5f6-3dcedf2be6e8.png">

**Comment by saintdianabless** [comment]
After a brief glance, https://github.com/Tencent/LuaHelper/blob/cc916454171f5d70f18ff2bc6229ba2059d5b9f0/luahelper-lsp/langserver/online_report.go#L8 will be uploaded if this option is checked(check the img below), or it will only upload your system version for counting the number of people online. coding as an online game?
![image](https://user-images.githubusercontent.com/93075932/213572993-f5b044e0-5c1e-4768-a14a-8d547ebd723a.png)

But it looks like there is no option to completely forbid the connection, maybe you could fork the repo and comment out this line
https://github.com/Tencent/LuaHelper/blob/cc916454171f5d70f18ff2bc6229ba2059d5b9f0/luahelper-lsp/langserver/initialize.go#L223

**Comment by melMass** [comment]
Thanks for the insights! I guess it's just basic analytics, I wish there was an option to just remove it all together.
Do they accept PRs?

**Comment by melMass** [comment]
I'll PR it and see if it's accepted!
