### ISSUE TITLE
无法正确识别多层注释

### ISSUE THREAD

**Issue by UnsterblichW** [Tencent/LuaHelper#166]
![image](https://user-images.githubusercontent.com/49482803/231327528-20afddb8-96bd-4252-b9c9-60db9577e5b9.png)
我的本意是将 106行 至 125行 都注释掉，但仅仅置灰了一小部分的代码。

**Comment by lalawue** [comment]
106 匹配到了 117 行，类似下面这样，输出是 nil

```lua
--[[
--[[
a = 12
--]]
print(a)
--]]
```

**Comment by UnsterblichW** [comment]
>
