### ISSUE TITLE
---[[语法检查异常

### ISSUE THREAD

**Issue by danggui1995** [Tencent/LuaHelper#178]
改为--[[ 就对了
![image](https://github.com/Tencent/LuaHelper/assets/15317581/e6988ace-b191-4c46-8fed-2d403519d9ee)

**Comment by AmeroHan** [comment]
根本没有`---[[`语法，你是从哪学的？

**Comment by HanaHye** [comment]
[https://www.lua.org/pil/1.3.html](https://www.lua.org/pil/1.3.html)

**Comment by danggui1995** [comment]
> 根本没有`---[[`语法，你是从哪学的？

一本正经的胡说八道
