### ISSUE TITLE
用不了了。。。如图，启动就报错

### ISSUE THREAD

**Issue by dycydyc** [Tencent/LuaHelper#189]
![微信截图_20231125124903](https://github.com/Tencent/LuaHelper/assets/48679770/00761fa0-c2ef-4b3f-b4e4-04519be1d324)

**Comment by yinfei8** [comment]
在输出框内有具体的报错的，具体的报错能贴下吗？

**Comment by dycydyc** [comment]
> 在输出框内有具体的报错的，具体的报错能贴下吗？

![微信截图_20231227002303](https://github.com/Tencent/LuaHelper/assets/48679770/432aa67b-7bd4-48cf-8734-c27aa2d224de)
是指这个吗

**Comment by dycydyc** [comment]
我把yinfei.luahelper-0.2.24那个文件夹删了，重装了一下，似乎能用了，神奇
