### ISSUE TITLE
LuaHelper-DebugFile

### ISSUE THREAD

**Issue by yangdehui** [Tencent/LuaHelper#28]
LuaHelper-DebugFile 一闪而过 不起作用，麻烦给看看休息 ，luaPath/packagePath填写什么呢
        {
            "type": "LuaHelper-Debug",
            "request": "launch",
            "name": "LuaHelper-DebugFile",
            "luaPath": "",
            "packagePath": [],
            "luaFileExtension": "cocos2dx",
            "connectionPort": 8818,
            "stopOnEntry": true,
            "useCHook": true,
            "logLevel": 1
        }

**Comment by kaishiqi** [comment]
cocos2dx工程么？那么为啥不配置 program 参数呢

**Comment by kaishiqi** [comment]
```json
{
            "type": "LuaHelper-Debug",
            "request": "launch",
            "name": "LuaHelper-Attach",
            "luaPath": "",
            "packagePath": [],
            "program": "${workspaceFolder}/../runtime/DemoMac.app/Contents/MacOS/DemoMac",
            "args": [
                "-workdir ${workspaceFolder}/../",
                "-position 865,1455"
            ],
            "luaFileExtension": "",
            "connectionPort": 8818,
            "stopOnEntry": false,
            "useCHook": false,
            "logLevel": 1
        }
```
我是这样配置，另外，main.lua中记得调用如下这句话，不然即便调试启动后也会无法断点。

```lua
-- 调试依赖
require("LuaPanda").start("127.0.0.1", 8818)
```

**Comment by yinfei8** [comment]
调试单文件已经重新了优化了，麻烦再试下。
