### ISSUE TITLE
luaHelper.setFormatConfig' not found

### ISSUE THREAD

**Issue by evepoe** [Tencent/LuaHelper#30]
luaHelper.setFormatConfig' not found
![luahelpererror](https://user-images.githubusercontent.com/251585/130045508-4bbcff11-50cf-452f-8825-fb172d02b4ae.png)

**Comment by yinfei8** [comment]
Formatting settings have been changed.
![image](https://user-images.githubusercontent.com/4758080/141630836-4380ba4c-01be-406c-8c64-91ee1d023d93.png)

**Comment by yinfei8** [comment]
代码格式化增加了设置
