### ISSUE TITLE
新版本的vscode,---快捷生成函数注释的功能失效

### ISSUE THREAD

**Issue by weiyuan-19** [Tencent/LuaHelper#44]
在vs code1.54之后，handleGenerateComment就失效了。
没有忽略分析文件或文件夹；
在lua function 上输入-- 或者 ---并没有出现generate document comments for the function，
但---@还是可以使用的

**Comment by weiyuan-19** [comment]
vscode1.54之后的版本，就没有这个快捷函数注释了

**Comment by yinfei8** [comment]
多谢反馈，验证了下确实是一个bug，这个bug会尽快修复。

**Comment by yinfei8** [comment]
最新的0.2.2版本修复了上面的问题

**Comment by weiyuan-19** [comment]
已测试可用，非常感谢
