### ISSUE TITLE
return定义的的类型无法传递出来了！

### ISSUE THREAD

**Issue by kaishiqi** [Tencent/LuaHelper#46]
```lua
---@class MyModel
    local myModel = class('MyModel')

    ---@return MyModel
    function getMyModel()
        return myModel
    end

    local model = getMyModel()  -- type is any ??
```

麻烦作者抽看看一下，是不是之前改出bug了？
这还是非常常用的提示功能，听影响coding的。

**Comment by yinfei8** [comment]
我这边无法重现，表现是对的，你是安装的哪一个版本?
![image](https://user-images.githubusercontent.com/4758080/141723381-a97180bb-364c-4e05-8deb-830a147de501.png)

**Comment by kaishiqi** [comment]
找了2台mac和1台win，使用的都是最新的0.2.2版本插件，结果表现都是返回any

**Comment by kaishiqi** [comment]
<img width="1532" alt="image" src="https://user-images.githubusercontent.com/2201159/141748861-82e57bce-36aa-4764-94c4-8db539fc3d43.png">
应该没有luaHelper的报错吧

**Comment by yinfei8** [comment]
> <img alt="image" width="1532" src="https://user-images.githubusercontent.com/2201159/141748861-82e57bce-36aa-4764-94c4-8db539fc3d43.png">
> 
> 应该没有luaHelper的报错吧

你加下我的QQ：313745207，我仔细定位下

**Comment by yinfei8** [comment]
引入了另外一个bug：self函数赋值的变量无法推导
![image](https://user-images.githubusercontent.com/4758080/141783474-310f17f4-e1ca-4de5-bc61-819408ee6851.png)

**Comment by kaishiqi** [comment]
> 引入了另外一个bug：self函数赋值的变量无法推导
> ![image](https://user-images.githubusercontent.com/4758080/141783474-310f17f4-e1ca-4de5-bc61-819408ee6851.png)

对了对了，是这个现象了，看来要成员函数才能复现，看来我举例的那个demo不合适，碰巧证明了单文件打开的推导的问题

**Comment by yinfei8** [comment]
@kaishiqi 
最新的0.2.3 版本修复了上面的bug

**Comment by kaishiqi** [comment]
亲测已修复，辛苦作者了~
