### ISSUE TITLE
[bug] 执行文件时未加入双引号以及“luaPath”定义无效

### ISSUE THREAD

**Issue by FlyingStarlight** [Tencent/LuaHelper#47]
VSCode Version: 1.62.2
Extension Version: v0.2.2

问题描述：
在独立文件调试模式中
1. 当系统登陆用户名含有空格时，其路径事例类似：”C:/Users/USER 1“，这种情况下当Lua Helper执行自身路径下的Lua5.4.exe时未加入双引号，致使CMD/PS因存在空格无法执行对应文件，表现为
`'c:/Users/USER' 不是内部或外部命令，也不是可运行的程序或批处理文件。`
建议加入双引号或者使用%USERPROFILE%

2. 为了解决问题1，我尝试修改launch.json中的luaPath为
`%USERPROFILE%/.vscode/extensions/yinfei.luahelper-0.2.2/debugger/luasocket/win/x64/lua5.4/lua54.exe`
后执行调试发现没有变化，遂改成说明中默认的
`"C:/lua5.3/lua.exe"`
发现执行调试时的命令行依旧无变化
提示该配置没有起到正确作用

**Comment by yinfei8** [comment]
![image](https://user-images.githubusercontent.com/4758080/141756137-30bdc102-4371-4b8d-9ff3-bde1b92abfb1.png)

**Comment by FlyingStarlight** [comment]
并不行，改成
`C:\\lua53.exe`
也并没有正确调用路径，还是以Lua Helper默认路径执行

**Comment by yinfei8** [comment]
@FlyingStarlight 
你C盘下面有lua53.exe吗？

**Comment by yinfei8** [comment]
@FlyingStarlight 
麻烦下载最新的版本0.2.3兼容了/ 路径

**Comment by FlyingStarlight** [comment]
> @FlyingStarlight 你C盘下面有lua53.exe吗？

不是有没有lua53.exe的问题
是在终端(PS/CMD)执行的指令就没有根据luaPath产生变化
新版本仍然无效，执行的命令仍为
`c:/Users/EXAMPLE USER/.vscode/extensions/yinfei.luahelper-0.2.3/debugger/luasocket/win/x64/lua5.4/lua54.exe -e  "package.path = 'c:/Users/EXAMPLE USER/.vscode/extensions/yinfei.luahelper-0.2.3/debugger/?.lua;'.. package.path;  package.cpath = 'c:/Users/"EXAMPLE USER"/.vscode/extensions/yinfei.luahelper-0.2.3/debugger/luasocket/win/x64/lua5.4/?.dll;'.. package.cpath; require('LuaPanda').start('127.0.0.1',8818);" "e:/MY/Lua/Test/test.lua"`
期待结果为：
`**c:/lua53.exe** -e  "package.path = 'c:/Users/EXAMPLE USER/.vscode/extensions/yinfei.luahelper-0.2.3/debugger/?.lua;'.. package.path;  package.cpath = 'c:/Users/"EXAMPLE USER"/.vscode/extensions/yinfei.luahelper-0.2.3/debugger/luasocket/win/x64/lua5.4/?.dll;'.. package.cpath; require('LuaPanda').start('127.0.0.1',8818);" "e:/MY/Lua/Test/test.lua"`

**Comment by FlyingStarlight** [comment]
我看到插件源码怎么写了，自动判断了路径内找不到`getLuaBinVersion`就用默认
测试实际放一个lua53.exe在对应路径没问题
那看看怎么解决`USER 1`不能识别的问题吧，用新版插件仍存在这个问题

**Comment by yinfei8** [comment]
@FlyingStarlight 
看到现象了，之前不方便构造你的场景。你加下QQ群：747590892

**Comment by MrScallion** [comment]
windows上 getLuaBinVersion 可以通过执行lua -e "print(_VERSION)" 来获取版本号，直接执行lua -v会获取不到输出，其他操作系统没有试过
