### ISSUE TITLE
VSCode plugin connects to 42.194.136.76

### ISSUE THREAD

**Issue by stawiski** [Tencent/LuaHelper#49]
Hi,

What's the reason the plugin opens a connection to `42.194.136.76`?
Is it to just show the number of active users?

Cheers

**Comment by yinfei8** [comment]
yes, it is.

**Comment by kasuganosoras** [comment]
能否关闭此功能？公司内网限制了对外 IP 连接，插件一直在报错

**Comment by yinfei8** [comment]
> 能否关闭此功能？公司内网限制了对外 IP 连接，插件一直在报错

增加了一个配置，可以单独关闭：
![image](https://user-images.githubusercontent.com/4758080/160526212-9eb2c4bd-bddc-473b-a440-9d45eca9daeb.png)
