### ISSUE TITLE
代码格式化功能失效

### ISSUE THREAD

**Issue by M1NGS** [Tencent/LuaHelper#51]
从0.16.2至最新版0.2.4都无法正常工作，打开日志后，选择格式化代码无任何日志输出

**Comment by yinfei8** [comment]
> 从0.16.2至最新版0.2.4都无法正常工作，打开日志后，选择格式化代码无任何日志输出

无任何日志输出是什么含义？你的环境是windows、linux还是mac？

**Comment by M1NGS** [comment]
> > 从0.16.2至最新版0.2.4都无法正常工作，打开日志后，选择格式化代码无任何日志输出
> 
> 无任何日志输出是什么含义？你的环境是windows、linux还是mac？

Win10+WSL2，无日志输出是指在打开服务端日志后，其他LuaHelper的功能执行时都有日志输出，右键呼出菜单也有日志输出，但点选格式化文档时，没有日志输出，此时VSCode文件标签页底部进度条开始滚动，但通过对WSL2的进程监控来看luaformatter没有被呼起。

VSCode版本：1.62.2
WSL2：Ubuntu 20.04.3 LTS@5.10.16.3-microsoft-standard-WSL2

**Comment by saintdianabless** [comment]
linux下的lua-format有问题
```bash
$ ./lua-format -i test.lua
terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory
Aborted (core dumped)

$ tree
.
├── core
├── lua-format
└── test.lua

0 directories, 3 files
```

**Comment by saintdianabless** [comment]
我编译了最新的[Koihik/LuaFormatter](https://github.com/Koihik/LuaFormatter)，然后替换`~/.vscode-server/extensions/yinfei.luahelper-0.2.4/server/linux`下的lua-format，是可以正常使用的

**Comment by M1NGS** [comment]
> 我编译了最新的[Koihik/LuaFormatter](https://github.com/Koihik/LuaFormatter)，然后替换`~/.vscode-server/extensions/yinfei.luahelper-0.2.4/server/linux`下的lua-format，是可以正常使用的

确实我的也是这个问题，不过我没开coredump，那天测试的时候以为只是一个warning
今天又看了一下，打印了返回码，是134(SIGABRT)


terminate called after throwing an instance of 'std::experimental::filesystem::v1::__cxx11::filesystem_error'
  what():  filesystem error: directory iterator cannot open directory: No such file or directory
Aborted

**Comment by saintdianabless** [comment]
@yinfei8  看下[这里](https://github.com/Tencent/LuaHelper/blob/e112dfa5a2a1eba2477a7d41bee687d417825d7f/luahelper-vscode/src/luaformat.ts#L335)和[这里：Event: 'exit'](https://nodejs.org/api/child_process.html#child_process_event_exit)，SIGABRT时code为null

**Comment by yinfei8** [comment]
> 我编译了最新的[Koihik/LuaFormatter](https://github.com/Koihik/LuaFormatter)，然后替换`~/.vscode-server/extensions/yinfei.luahelper-0.2.4/server/linux`下的lua-format，是可以正常使用的

多谢反馈，知道原因了，编译的linux lua-fmt有点问题，明天更新下。

**Comment by yinfei8** [comment]
> > > 从0.16.2至最新版0.2.4都无法正常工作，打开日志后，选择格式化代码无任何日志输出
> > 
> > 
> > 无任何日志输出是什么含义？你的环境是windows、linux还是mac？
> 
> Win10+WSL2，无日志输出是指在打开服务端日志后，其他LuaHelper的功能执行时都有日志输出，右键呼出菜单也有日志输出，但点选格式化文档时，没有日志输出，此时VSCode文件标签页底部进度条开始滚动，但通过对WSL2的进程监控来看luaformatter没有被呼起。
> 
> VSCode版本：1.62.2 WSL2：Ubuntu 20.04.3 LTS@5.10.16.3-microsoft-standard-WSL2

多谢反馈，知道原因了，编译的linux lua-fmt有点问题，明天更新下。
