### ISSUE TITLE
[Feature] 添加 PathSeparator 设置选项

### ISSUE THREAD

**Issue by Legend-Master** [Tencent/LuaHelper#52]
现在看上去只能通过luahelper.json来设置这个选项，不能给工作区或者全局应用

**Comment by yinfei8** [comment]
> 现在看上去只能通过luahelper.json来设置这个选项，不能给工作区或者全局应用

请问你需要设置PathSeparator 的具体场景是？

**Comment by Legend-Master** [comment]
> > 现在看上去只能通过luahelper.json来设置这个选项，不能给工作区或者全局应用
> 
> 请问你需要设置PathSeparator 的具体场景是？

我在做 Don't Starve Together 的 Mod ，他们用的 loader 只支持用 / 来分隔不支持用 . ，因为在做的 Mod 不止一个，每个文件夹里面放一个 luahelper.json 有点麻烦，就在想能不能做到设置里直接在用户里把分隔符都换成 /

**Comment by yinfei8** [comment]
> 现在看上去只能通过luahelper.json来设置这个选项，不能给工作区或者全局应用

能否加下我的QQ：313745207，详细了解下。

**Comment by yinfei8** [comment]
最新的0.2.6版本增加了一个设置
![image](https://user-images.githubusercontent.com/4758080/142999721-1ceea80a-bf28-4d3c-9450-3c39b72a87e4.png)

**Comment by yinfei8** [comment]
最新版本已经增加了设置
