### ISSUE TITLE
无法调试

### ISSUE THREAD

**Issue by 492869397** [Tencent/LuaHelper#58]
require("socket.core")

PS D:\UserProfiles\Menu\Desktop\test> lua -e  "package.path = 'c:/Users/MengyuZhang/.vscode/extensions/yinfei.luahelper-0.2.7/debugger/?.lua;'.. package.path;  package.cpath = 'c:/Users/MengyuZhang/.vscode/extensions/yinfei.luahelper-0.2.7/debugger/luaso/MengyuZhang/.vscode/extensions/yinfei.luahelper-0.2.7/debugger/luasocket/win/x64/lua5.3/?.dll;'.. package.cpath; require('LuaPanda').start('127.0.0.1',8818);" "d:/UserProfiles/MengyuZhang/Desktop/test/test.lua"
[LuaPanda] [Error] reGetSock fail
[LuaPanda] [Error] Start debugger but get Socket fail , please install luasocket!
C:\Program Files\lua\lua.exe: error loading module 'socket.core' from file 'c:/Users/MengyuZhang/.vscode/extensions/yinfei.luahelper-0.2.7/debugger/luasocket/win/x64/lua5.3/socket\core.dll':  
        %1 不是有效的 Win32 应用程序。

require socket的时候可以看到这个报错。单个文件调试的时候会这样。 
项目里也不能调试，可能也是这个原因

**Comment by yinfei8** [comment]
你本地装的Lua是32位还是64位？看日志是lua5.3版本

**Comment by 492869397** [comment]
听君一席话，胜读一席话。删除了原来自己装的lua，就可以调试单个文件了。项目里的有时间再试试
