### ISSUE TITLE
require中的路径跳转功能失效

### ISSUE THREAD

**Issue by weiyuan-19** [Tencent/LuaHelper#60]
lua helper 0.2.8
require 中的路径无法跳转到文件中

**Comment by weiyuan-19** [comment]
测试0.2.6可用
0.2.7后不能跳转

**Comment by yinfei8** [comment]
> 测试0.2.6可用 0.2.7后不能跳转

你的场景是不是这样
local one = require("one")
实际上，是包含的 one/init.lua 文件？

**Comment by yinfei8** [comment]
> 测试0.2.6可用 0.2.7后不能跳转

多谢反馈，确实是一个新版本的bug。
在0.2.9最新版本修复了，麻烦再更新下。

**Comment by weiyuan-19** [comment]
已测试可用，非常感谢！
