### ISSUE TITLE
Run lua-format failed with exit code: 3221225595

### ISSUE THREAD

**Issue by GFDGIT** [Tencent/LuaHelper#66]
插件版本：0.2.9
VSCode版本: 1.62.3
OS: Windows_NT x64 10.0.19043

格式化报错，开启日志也没有报错输出。
直接执行 `extensions\yinfei.luahelper-0.2.9\server\win32\lua-format.exe` 
提示 “应用程序无法正常启动(0xc000007b)”

使用[vscode-lua-format](https://github.com/Koihik/vscode-lua-format)格式化，一切正常。

可能是插件自带 **lua-format.exe** 有问题？

**Comment by yinfei8** [comment]
你这个问题是一个比较通用的问题：https://www.win10zjb.com/win10jc/12869.html
看了下vscode-lua-format它编译的是windows 64位二进制，后面的插件版本，我把二进制也升级成64位试下。

**Comment by GFDGIT** [comment]
问题解决了，我装了vc++ 2015-2022 x86的依赖就没问题了。

一看到“应用程序无法正常启动(0xc000007b)”，我就想可能是vc++依赖的问题，再看 lua-format.exe 用的c++17编译的，我已经装了vc++ 2019 x64了，就想应该不是依赖问题。

再看，你编译的是32位版本，就试着装了32位的依赖，一切正常了。

建议readme提一下vc++依赖的问题。

**Comment by yinfei8** [comment]
> 问题解决了，我装了vc++ 2015-2022 x86的依赖就没问题了。
> 
> 一看到“应用程序无法正常启动(0xc000007b)”，我就想可能是vc++依赖的问题，再看 lua-format.exe 用的c++17编译的，我已经装了vc++ 2019 x64了，就想应该不是依赖问题。
> 
> 再看，你编译的是32位版本，就试着装了32位的依赖，一切正常了。
> 
> 建议readme提一下vc++依赖的问题。
你安装的vc++ 2015-2022 x86具体链接是？
能发下吗？

**Comment by GFDGIT** [comment]
Microsoft Visual C++ 可再发行程序包最新支持的下载 [https://docs.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170](https://docs.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170)
