### ISSUE TITLE
Can't find luasocket?

### ISSUE THREAD

**Issue by NickGrease** [Tencent/LuaHelper#8]
I'm sorry, I'm very new to Lua and don't really understand what the problem is here. 
![vscode1](https://user-images.githubusercontent.com/854582/90967072-0f446280-e4a8-11ea-9826-4ab2f7fe50ff.png)
![vscode2](https://user-images.githubusercontent.com/854582/90967073-0f446280-e4a8-11ea-8340-92cb26b0a850.png)
![vscode3](https://user-images.githubusercontent.com/854582/90967074-0f446280-e4a8-11ea-98ab-8e233f5a3157.png)
![vscode4](https://user-images.githubusercontent.com/854582/90967075-0fdcf900-e4a8-11ea-9855-7da8c156e28e.png)

**Comment by yinfei8** [comment]
We have fixed the problem in the last version.

**Comment by MarioRicalde** [comment]
This issue somewhat helped me by getting me to build my own Lua 5.4 luasockets `socket/core.dll` - after loading it in place of the provided one everything works.

**Comment by MarioRicalde** [comment]
For added clarity: 

For those experiencing issues with luasocket, here's what worked for me to get the debugger working on Windows 11:

Download the Lua (5.4) Interpreter an put it somewhere to use it, in my case `/C/Users/MarioRicalde/OneDrive/Documents/Lua/`

Install MSYS2 https://www.msys2.org/#installation

In the MSYS terminal and install the toolchain:

pacman -S mingw-w64-x86_64-toolchain

Download latest release (src) or clone from https://github.com/lunarmodules/luasocket/releases.

Using Msys2 mingw64 and navigate to directory, adjust the paths to match your configuration (hint, replace C/Users/MarioRicalde/OneDrive/Documents with your path ):

```bash
x86_64-w64-mingw32-gcc -O2 -c -o src/luasocket.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/luasocket.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/timeout.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/timeout.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/buffer.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/buffer.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/io.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/io.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/auxiliar.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/auxiliar.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/options.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/options.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/inet.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/inet.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/except.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/except.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/select.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/select.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/tcp.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/tcp.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/udp.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/udp.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/compat.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/compat.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
x86_64-w64-mingw32-gcc -O2 -c -o src/wsocket.o -I/C/Users/MarioRicalde/OneDrive/Documents/Lua/include/lua/5.4 src/wsocket.c -DLUASOCKET_DEBUG -DWINVER=0x0501 -I/c/windows/system32/include
mkdir socket
x86_64-w64-mingw32-gcc  -shared -o socket/core.dll src/luasocket.o src/timeout.o src/buffer.o src/io.o src/auxiliar.o src/options.o src/inet.o src/except.o src/select.o src/tcp.o src/udp.o src/compat.o src/wsocket.o -lws2_32 /C/Users/MarioRicalde/OneDrive/Documents/Lua/lua54.dll -lm
```

With that you should have the core.dll file:

```bash
MarioRicalde@MR-WS MINGW64 /c/Users/MarioRicalde/OneDrive/Documents/Lua/other/luasocket-3.1.0
$ ls socket
core.dll
```

Go to VSCode, Ctrl + P, write:

 > LuaHelper: Open Debug Folder

That will open explorer, go into luasocket > win > x64 > lua5.4 > socket

Rename core.dll to core.bak.dll and add your newly compiled core.dll

Go back into VSCode and test.
