### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by leolovenet** [Tencent/LuaHelper#80]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x7fc9c6]

goroutine 443 [running]:
luahelper-lsp/langserver/check/common.(*Symbol).GetLine(...)
	/data/yvanfyin/github/luahelper-lsp/langserver/check/common/var_info.go:153
luahelper-lsp/langserver/check.(*AllProject).symbolHasSubKey(0xc0004d2a80, 0x0, 0xc03a0d64a6, 0x7, 0xc000a3be50, 0xc019d71680, 0x1)
	/data/yvanfyin/github/luahelper-lsp/langserver/check/check_find_var_refer.go:423 +0x46
luahelper-lsp/langserver/check.(*AllProject).getDeepVarList(0xc0004d2a80, 0x0, 0xc019d71920, 0xc000a3be50, 0xc000a3be00, 0xc000a3be50, 0xc019d71700)
	/data/yvanfyin/github/luahelper-lsp/langserver/check/check_lsp_annotate.go:1345 +0x145
luahelper-lsp/langserver/check.(*AllProject).FindVarDefine(0xc0004d2a80, 0xc03a0d6360, 0x2e, 0xc019d71920, 0x1, 0x0, 0x0, 0x0)
	/data/yvanfyin/github/luahelper-lsp/langserver/check/check_lsp_define.go:429 +0x19c
luahelper-lsp/langserver/check.(*AllProject).FindVarDefineInfo(0xc0004d2a80, 0xc03a0d6360, 0x2e, 0xc019d71920, 0x3d00000011, 0x11, 0x3d)
	/data/yvanfyin/github/luahelper-lsp/langserver/check/check_lsp_define.go:258 +0x6d
luahelper-lsp/langserver.(*LspServer).TextDocumentDefine(0xc00021e460, 0x9dad00, 0xc03a0d1260, 0xc039b70ec0, 0x35, 0x3d00000011, 0x0, 0x0, 0x0, 0x0, ...)
	/data/yvanfyin/github/luahelper-lsp/langserver/textdocument_define.go:60 +0x4da
reflect.Value.call(0x8ba580, 0xc000206200, 0x13, 0x93dbf9, 0x4, 0xc03a0d1290, 0x2, 0x2, 0x10, 0x18, ...)
	/usr/lib/golang/src/reflect/value.go:476 +0x8c7
reflect.Value.Call(0x8ba580, 0xc000206200, 0x13, 0xc03a0d1290, 0x2, 0x2, 0x2, 0xc03a0d1290, 0x1)
	/usr/lib/golang/src/reflect/value.go:337 +0xb9
github.com/yinfei8/jrpc2/handler.newHandler.func8(0x9dad00, 0xc03a0d1260, 0xc0112f2f00, 0x904ec0, 0xc03a0d1260, 0x8c0f00, 0xc9f298)
	/data/yvanfyin/go/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/handler/handler.go:240 +0x1f2
github.com/yinfei8/jrpc2/handler.Func.Handle(0xc000205d60, 0x9dad00, 0xc03a0d1260, 0xc0112f2f00, 0x0, 0x0, 0x9dad00, 0xc03a0d1260)
	/data/yvanfyin/go/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/handler/handler.go:23 +0x44
github.com/yinfei8/jrpc2.(*Server).invoke(0xc000254000, 0x9dac40, 0xc0112f2fc0, 0x9d2f00, 0xc000205d60, 0xc0112f2f00, 0x0, 0x0, 0x0, 0x0, ...)
	/data/yvanfyin/go/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:347 +0x19d
github.com/yinfei8/jrpc2.(*Server).dispatch.func1.1()
	/data/yvanfyin/go/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:229 +0xe5
created by github.com/yinfei8/jrpc2.(*Server).dispatch.func1
	/data/yvanfyin/go/pkg/mod/github.com/yinfei8/jrpc2@v0.13.1/server.go:232 +0x14d
[Info  - 11:37:48 AM] Connection to server got closed. Server will restart.
[Error - 11:37:49 AM] Request textDocument/definition failed.

**Comment by yinfei8** [comment]
Thank you for your feedback, the latest version has been fixed it.
