### ISSUE TITLE
"onDebug" should be removed from the "Activation Events" list ?

### ISSUE THREAD

**Issue by leolovenet** [Tencent/LuaHelper#89]
在其他语言的项目下，只要调试，就会激活该插件，其实本不应该这样。
Under projects in other languages, just debugging will activate the plugin, which should not be the case
<img width="423" alt="image" src="https://user-images.githubusercontent.com/2268675/159410353-e00d5523-7137-4b1b-9782-8673c0411d65.png">

**Comment by yinfei8** [comment]
请问，你上面的UI界面是如何调试出来的？

**Comment by leolovenet** [comment]
<img width="983" alt="image" src="https://user-images.githubusercontent.com/2268675/160386663-29317dbf-0b03-4c0a-90fc-94aa5c064bef.png">

**Comment by yinfei8** [comment]
多谢反馈，找到了，下一个版本修复这个。

**Comment by yinfei8** [comment]
多谢反馈，找到了，这个星期的版本会修复这个。

**Comment by yinfei8** [comment]
最新的版本0.2.12修复了
![image](https://user-images.githubusercontent.com/4758080/160525692-212d13be-ed99-4474-a998-e3fd8536d33a.png)
