### ISSUE TITLE
函数注解

### ISSUE THREAD

**Issue by nieyanbing** [Tencent/LuaHelper#91]
```
---@param p1 number @
---@param p2 number | nil @
local function func(p1, p2)
    p2 = p2 or 100
    print(p1, p2)
end
```
期望p2可以不写,不写的话会自动给一个默认值
如果加了注解但是不写p2的话 会报错
这种应该怎么写

**Comment by yinfei8** [comment]
你说的意思是，其他地方调用func时只传了一个参数，会报参数少于2的告警？
可以这样

---@param p1 number @
---@param p2? number @
local function func(p1, p2)
    p2 = p2 or 100
    print(p1, p2)
end

**Comment by nieyanbing** [comment]
可以了 谢谢
