### ISSUE TITLE
今天更新了0.2.13后报错了

### ISSUE THREAD

**Issue by stephenmax-zhang** [Tencent/LuaHelper#95]
如题，宿主机centos
[Info  - 上午10:52:06] Connection to server got closed. Server will restart.
/home/zhangjie/.vscode-server/extensions/yinfei.luahelper-0.2.13/server/linuxlualsp: /home/zhangjie/.vscode-server/extensions/yinfei.luahelper-0.2.13/server/linuxlualsp: 无法执行二进制文件
[Error - 上午10:52:06] Connection to server is erroring. Shutting down server.
[Error - 上午10:52:06] Connection to server got closed. Server will not be restarted.
/home/zhangjie/.vscode-server/extensions/yinfei.luahelper-0.2.13/server/linuxlualsp: /home/zhangjie/.vscode-server/extensions/yinfei.luahelper-0.2.13/server/linuxlualsp: 无法执行二进制文件

**Comment by yinfei8** [comment]
不好意思，确实是有问题，麻烦再升级到0.2.14版本。
